### ISSUE TITLE
DatabaseTokenSelection.selectTokens doesn't see newly issued tokens

### ISSUE THREAD

**Issue by adelRestom** [corda/token-sdk#171] opened 2020-01-08 21:35 UTC
**Corda: CE 4.3**
**Tokens: 1.1-RC01**

My design is as following:  
1. I have 2 nodes: Mint and Wallet.
2. Mint creates new tokens (calls `IssueTokens` to itself).
3. Wallet has user accounts (Account library).
4. Mint has a flow to issue tokens to accounts on Wallet (calls `MoveFungibleTokens`).
5. Mint doesn't create a circulating supply then use it, meaning I don't create 1000,000 tokens then use them, instead; the Mint mints as you go.
6. If the Mint has balance, it will just transfer the required quantity to the account on Wallet.
7. If the Mint doesn't have enough balance, it will mint new tokens (i.e. issue to itself) then move the required amount to Wallet.
8. Please note that for better performance I mint extra tokens, meaning if the Mint is short of 5 tokens, I mint 100; so next time the Mint wants to issue to an account; it will most probably have balance. Anyway...

The problem is in the following flow test scenario:
1. The Mint node has balance of 10.
2. I call the issue flow to issue 90 tokens to an account.
3. The Mint will mint 100 new tokens (issue to itself).
4. The Mint will transfer 90 tokens to the account on Wallet.
5. The Mint's new balance is 10 + 100 - 90 = 20.

The problem is in step 4, I ran the test in debug mode and reached `DatabaseTokenSelection.selectTokens` and when it queries the vault, it only sees 10 tokens:

![image](https://user-images.githubusercontent.com/37046080/72017206-dc0bd680-322a-11ea-89ff-dfd73392baaa.png)

Even though when I query the vault, I can see the 110 tokens (i.e. initial balance of 10 + newly minted 100). I have a function that does that before and after minting, so my flow steps were:
1. Check Mint balance -> returned <false, Mint balance: 10> (false, as in it doesn't have enough balance)
2. Mint new tokens
3. Check Mint balance -> returned <true, Mint balance: 110> (true because now it has enough balance)
4. Call `MoveFungibleTokens` which fails because again `DatabaseTokenSelection.selectTokens` only sees the initial 10 tokens balance which is not enough to transfer the requested 90.

![image](https://user-images.githubusercontent.com/37046080/72017933-5557f900-322c-11ea-99f6-a60a6ade15be.png)

**Comment by roger3cev** [comment] 2020-01-09 09:38
Thanks for the bug report.

Unfortunately we can't really do much without seeing your code. Do you have this reproduced anywhere? At a minimum it would be good to see your query criteria. Also how you generate change keys for the various moves you do.

How are you running the test? Mock Network or node driver?

**Comment by roger3cev** [comment] 2020-01-09 09:40
Also, the "10" you have circled in the image above is the size of the `ArrayList`, not the token balance.

**Comment by adelRestom** [comment] 2020-01-09 13:53
1. I can't share my code, I will work on a sample project that has the same code.
2. Yes, it's the size of the array; but I only issue tokens where the quantity is 1, so the size does represent the balance (10 states = 10 tokens).

**Comment by roger3cev** [comment] 2020-01-09 15:12
Oh wow, ok. In that case then I'll await your example. Cheers

**Comment by adelRestom** [comment] 2020-01-09 17:42
1. I built an example: https://github.com/adelRestom/tokens-sdk-issue-171.
2. The example uses a fixed token (USD).
3. The test fails for both `1.1-RC01` and `1.1-RC06-PRESIGN`.
4. Run the test `issueTest()` in debug mode and put a breakpoint inside `issueFixedToken` at line 81. You will see that the balance of the mint is updated:

![image](https://user-images.githubusercontent.com/37046080/72091061-f26e6c80-32d4-11ea-93fb-564b0a6e0a96.png)

5. Now put a breakpoint on `DatabaseTokenSelection` line 85, you'll see that the size of `results` is 0. Meaning the token selector doesn't see the newly minted tokens, even though they are in the vault.

![image](https://user-images.githubusercontent.com/37046080/72091145-221d7480-32d5-11ea-8abc-55dfb835930b.png)

**Comment by roger3cev** [comment] 2020-01-10 09:44
Thanks, I'll have a look...

**Comment by roger3cev** [comment] 2020-01-10 10:51
So you can get the first test to pass by replacing line `47` in `MintFixedToken.java`, which is:

        Amount<IssuedTokenType> amount = new Amount(quantity, issuedTokenType);

With:

        Amount<IssuedTokenType> amount = AmountUtilitiesKt.of(quantity, issuedTokenType);

Remember that `Amount`s are in cents and you should not use the Amount constructor when creating an amount otherwise the amount will be "out" by a factor of 100. Will look at the other test now...

**Comment by roger3cev** [comment] 2020-01-10 11:51
With the first test fixed. When the second test is run...

`validationResultBeforeMinting` is `true=10000` (a balance of 100.00)

Then the `MintFixedToken` flow is called. Once it completes then there are two token states in the vault. I used (`getServiceHub().getVaultService().queryBy(FungibleToken.class).getStates()`)... One of 100.00 (created in the previous test) and another of 10,000.00 just minted now.

`validationResultAfterMinting` is `true=1010000` (a balance of 10,100.00)

You then try to move 10,000 to the recipient, in theory, leaving 100.00 in the vault. However, the assertion at the end of your test returns 0 for the wallet balance because there is a race condition in your flow. At the point where move tokens tries to select the tokens, the vault hasn't actually updated with the newly created tokens. See the logs...

```
[WARN] 11:49:22,919 [Mock network] selector.DatabaseTokenSelection. - TokenType selection failed on attempt 1. {actor_id=Only For Testing, actor_owning_identity=O=Mint, L=London, C=GB, actor_store_id=TEST, fiber-id=10000002, flow-id=bf4b8dba-62d1-47dc-b344-353832bfd692, invocation_id=94bf64dc-2e4a-4a61-aa9c-73f63d1f8125, invocation_timestamp=2020-01-10T11:49:22.728Z, origin=Only For Testing, session_id=94bf64dc-2e4a-4a61-aa9c-73f63d1f8125, session_timestamp=2020-01-10T11:49:22.728Z, thread-id=422, tx_id=F1ECB575C22129A06129F7324146F29AD064E734D116532C187D832927E54B0B}
[INFO] 11:49:23,047 [Mock network] services.VaultWatcherService. - received token vault update with 0 consumed states and: 1 produced states {actor_id=Only For Testing, actor_owning_identity=O=Mint, L=London, C=GB, actor_store_id=TEST, fiber-id=10000002, flow-id=bf4b8dba-62d1-47dc-b344-353832bfd692, invocation_id=94bf64dc-2e4a-4a61-aa9c-73f63d1f8125, invocation_timestamp=2020-01-10T11:49:22.728Z, origin=Only For Testing, session_id=94bf64dc-2e4a-4a61-aa9c-73f63d1f8125, session_timestamp=2020-01-10T11:49:22.728Z, thread-id=422}
[WARN] 11:49:23,261 [Mock network] selector.DatabaseTokenSelection. - TokenType selection failed on attempt 2. {actor_id=Only For Testing, actor_owning_identity=O=Mint, L=London, C=GB, actor_store_id=TEST, fiber-id=10000002, flow-id=bf4b8dba-62d1-47dc-b344-353832bfd692, invocation_id=94bf64dc-2e4a-4a61-aa9c-73f63d1f8125, invocation_timestamp=2020-01-10T11:49:22.728Z, origin=Only For Testing, session_id=94bf64dc-2e4a-4a61-aa9c-73f63d1f8125, session_timestamp=2020-01-10T11:49:22.728Z, thread-id=422, tx_id=F1ECB575C22129A06129F7324146F29AD064E734D116532C187D832927E54B0B}
```

You should probably do the moving in another flow.

I don't think there is an issue with the token SDK. 

Cheers

**Comment by roger3cev** [comment] 2020-01-10 12:28
Follow up: actually there might be an issue with the token SDK in that the `SoftLockingCondition` is _always_ set to `UNLOCKED_ONLY` by the token selection module. This might conflict with what you are trying to do which is issue and move a token in the same flow. When states are produced, they are always produced in a `LOCKED` state so they cannot be stolen by other flows. So what we need to do to get your flow to work is use `SoftLockingCondition.UNLOCKED_AND_SPECIFIED` and I think that will work. Token SDK needs updating though. Cheers

**Comment by adelRestom** [comment] 2020-01-10 13:52
Thanx Roger for your reply:
1. I always use `AmountUtilitiesKt.of(quantity, issuedTokenType);`, I just tried to write a quick example that runs and shows the problem (this example is not production ready lol).
2. Any timelines about when's the next RC, and whether it will include this fix or not?

**Comment by roger3cev** [comment] 2020-01-10 14:15
We are looking to release tokens by the end of the month. As there is a workaround for this issue (by doing the move in another flow), I don't think we need to fix the issue in this version. I haven't actually confirmed this is the issue - we would need to do some testing first. Cheers

**Comment by roger3cev** [comment] 2020-01-10 14:25
Update: Can confirm that changing line `68` in `DatabaseTokenSelection.kt` from:

            softLockingType: QueryCriteria.SoftLockingType = QueryCriteria.SoftLockingType.UNLOCKED_AND_SPECIFIED

to

            softLockingType: QueryCriteria.SoftLockingType = QueryCriteria.SoftLockingType.UNLOCKED_ONLY

fixes the issue.

**Comment by roger3cev** [comment] 2020-01-10 14:36
Actually I just changed it. See https://github.com/corda/token-sdk/pull/173 

If all the tests pass then I'll merge it. 

Cheers

**Comment by roger3cev** [comment] 2020-01-10 14:51
Closing this as addressed now. Cheers

**Closed by roger3cev** 2020-01-10 14:51 UTC
Labels: bug

**Comment by adelRestom** [comment] 2020-01-10 15:09
That was quick; thanx Roger. 
So how do I use the new version of the SDK?
